server {
    listen 8080;
    root /usr/share/nginx/html;   # корень, где лежит rest-api-test

    index index.php index.html;

    # Все запросы к /tasks и /tasks/* перенаправляем на единую точку входа
    location /tasks {
        # Переписываем URI, передавая захваченный ID как GET-параметр 'id'
        # Если ID отсутствует, $1 будет пустой строкой (id=)
        rewrite ^/tasks(?:/(.*))?$ /rest-api-test/api/tasks.php?id=$1&$args last;
    }

    # Запрет доступа к каталогу config и всем его файлам
    location ^~ /rest-api-test/config/ {
        deny all;
        return 403;
    }

    # Обработка PHP-скриптов через FastCGI (PHP-FPM)
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        fastcgi_index			index.php;
        fastcgi_buffers			8 16k;
        fastcgi_buffer_size		32k;

        fastcgi_param DOCUMENT_ROOT	$realpath_root;
        fastcgi_param SCRIPT_FILENAME	$realpath_root$fastcgi_script_name;
    }
}
